#!/bin/bash
# COUNT DIRECTORIES IN A DIRECTORY AND DELETE OLDEST
# Verion 1
# Author: Rob Flemen
# Email: rob@marleylilly.com

# Script to count the number of directories in current directory
# and delete the oldest on if it exceeds the limit set.

current_dir=$(pwd)
date_stamp=$(date +%m-%d-%Y)
time_stamp=$(date +%H_%M_%S)
log_file_name="/home/mladmin/usb_backup/logs/${date_stamp}_clean_dir.log"
email_receipient="rob@marleylilly.com"


# Set maximum directories for current directory
max_dirs=6

# Determine the number of directories in current directory
num_of_dirs=$(ls -d */ | wc -l)

# Determine which of the directories is the oldest
oldest_dir=$(ls -dtr */ | head -n 1)

# Header for the logfile
echo "*************************************" >> "${log_file_name}"
echo "Backup Retention Correction Script" >> "${log_file_name}"
echo >> "${log_file_name}"
echo "*************************************" >> "${log_file_name}"
echo "Run Date & Time: ${date_stamp} at ${time_stamp}" >> "${log_file_name}"
echo >> "${log_file_name}"
echo "Current working directory is: ${current_dir}" >> "${log_file_name}"
echo >> "${log_file_name}"
echo "The number of directories allowed is: ${max_dirs}" >> "${log_file_name}"
echo >> "${log_file_name}"
echo "The current number of directories is: ${num_of_dirs}" >> "${log_file_name}"
echo >> "${log_file_name}"
echo "The oldest directory here is: ${oldest_dir}" >> "${log_file_name}"
echo >> "${log_file_name}"

#Check to see if we over linit and delete oldest directory, if needed
if [ $num_of_dirs -gt $max_dirs ]
then
        echo "We are over the limit so we're deleting ${oldest_dir}" >> "${log_file_name}"
        sleep 5
        rm -rf ${oldest_dir}
        if [ $? == 0 ]
        then
                echo "SUCCESS! ${oldest_dir} has been deleted!" >> "${log_file_name}"
                echo >> "${log_file_name}"
        else
                echo "Something went wrong!" >> "${log_file_name}"
                echo >> "${log_file_name}"
        fi
else
        echo "There aren't enough directories so there is nothing to do!!!" >> "${log_file_name}"
fi

# Send a copy of the logfile to interested parties
cat "${log_file_name}"  | sudo ssmtp "${email_receipient}"